/** @deprecated Import from features/social/models/social.model instead */
export type {
  ApiResponse,
  CarouselChildAttempt,
  CarouselChildStatus,
  CreateSocialPostPlanRequest,
  ExtendedPostTargetStatus,
  InstagramContentType,
  MetaCapabilities,
  MetaAccountsQuery,
  MetaConnectionInfo,
  MetaConnectionType,
  MetaDisconnectResponse,
  MetaManagedAccount,
  MetaOAuthStartResponse,
  MetaProvider,
  MetaStatus,
  MetaSyncResponse,
  PlanMediaItem,
  PlanMediaRole,
  PostDestination,
  ProviderOptionsInstagram,
  ProviderOptionsLinkedIn,
  PublishAttempt,
  PublishingQuota,
  SocialAccount,
  SocialAccountsQuery,
  SocialCapabilities,
  SocialConnectionType,
  SocialConnectionTypeStatus,
  SocialIntegrationCatalogItem,
  SocialIntegrationsStatus,
  SocialProvider,
  SocialProviderGroup,
  SocialProviderGroupStatus,
  SocialSyncResponse
} from '../../social/models/social.model';
